### ISSUE TITLE
[FeatureRequest] Allow to set TopicLinkIn by env

### ISSUE THREAD

**Issue by Hypnos3** [cinhcet/node-red-contrib-topic-link#1]
It would be nice to have the posibility to set the topic for the IN Node also by env variable. So I could have the In Node in a SubFlow, and allowed to configure the topic by env setting of the subflow. These settings needs to only evaluated during node start, because env variables not dynamically.

**Comment by Hypnos3** [comment]
is already implemented by setting topic to `${ENVIROMENT_VARIABLE}`

**Comment by cinhcet** [comment]
Thanks for commenting that!
